Make default search limit more prominent
meilisearch/documentation pull request #1228
Opened 2021-10-25 13:38 UTC by maryamsulemani97

closing #809

2021-11-04 13:44 UTC, dichotommy requested changes

2021-11-04 13:44 UTC, dichotommy commented on learn/getting_started/quick_start.md
> +By default, MeiliSearch returns the first **20 documents for a search query.** You can read more about the limit parameter [here](/reference/features/search_parameters.md#limit).
```suggestion
**By default, MeiliSearch returns only the first 20 results** for a search query. You can read more about the limit parameter [here](/reference/features/search_parameters.md#limit).
```

2021-11-04 13:46 UTC, dichotommy commented on learn/getting_started/quick_start.md
> +By default, MeiliSearch returns the first **20 documents for a search query.** You can read more about the limit parameter [here](/reference/features/search_parameters.md#limit).
When picking which text to **bold**, I aim to make the bolded text readable by itself. It should be a complete clause that communicates a clear piece of information. That way someone who's scrolling quickly can still catch the pertinent information and stop to investigate if it's relevant to them.

2021-11-04 15:36 UTC, CaroFG approved these changes

2021-11-15 10:18 UTC, guimachiavelli approved these changes

2021-11-16 12:22 UTC, guimachiavelli commented
👯

2021-11-16 12:24 UTC, dichotommy approved these changes
🚀

2021-11-16 12:24 UTC, guimachiavelli commented
bors merge

2021-11-16 12:25 UTC, merged