move update guide to learn>advanced topics
meilisearch/documentation pull request #1253
Opened 2021-11-08 16:10 UTC by maryamsulemani97

2021-11-10 10:38 UTC, guimachiavelli requested changes
Just needs a typo fix and a new line at the end and we're good to go 👽

2021-11-10 10:38 UTC, guimachiavelli commented on .vuepress/public/_redirects
> +/create/how_to/updating.md)                          /learn/advanced/updating.md
```suggestion
/create/how_to/updating.md                           /learn/advanced/updating.md

```

2021-11-22 12:52 UTC, dichotommy requested changes
Thanks for doing this, just a few changes 🙃

2021-11-22 12:52 UTC, dichotommy commented on .vuepress/config.js
> +            '/learn/advanced/updating.md',
Not 100% certain but pretty sure that if we don't specify a title, VuePress will use the first H1 in the file, which in this case is `# Update to the latest MeiliSearch version`. Seems a bit long to me, therefore I prefer:

```suggestion
            {
              title: 'Updating MeiliSearch',
              path: '/learn/advanced/updating.md'
            },
```

2021-11-22 12:52 UTC, dichotommy commented on .vuepress/public/_redirects
> +/create/how_to/updating.md                           /learn/advanced/updating.md
This redirection occurs through Netlify, so `.md` links will not work.

```suggestion
/create/how_to/updating.html                           /learn/advanced/updating.html
```

2021-11-22 12:52 UTC, dichotommy commented on index.md
> +- [Update MeiliSearch](/learn/advanced/updating.md)
```suggestion
- [Updating MeiliSearch](/learn/advanced/updating.md)
```

2021-11-22 13:51 UTC, dichotommy commented
Oops, because of my suggestion you're missing a comma on line 86 of `config.js`.

2021-11-22 17:27 UTC, guimachiavelli approved these changes
LGTM

2021-11-23 12:25 UTC, dichotommy approved these changes
LGTM 🤠👍🏻

2021-11-23 12:25 UTC, dichotommy commented
bors merge

2021-11-23 12:26 UTC, merged