add new errors
meilisearch/documentation pull request #1298
Opened 2021-11-22 13:54 UTC by maryamsulemani97

closes #1283

2021-11-24 17:05 UTC, gmourier requested changes
That's great! 

A take-it-or-leave-it idea, use `given` rather than `requested` in this case because we are sending a payload that is supposed to represent an API Key resource to the API. 🤓

2021-11-25 11:57 UTC, maryamsulemani97 commented
> we are sending a payload that is supposed to represent an API Key resource to the API

@gmourier I don’t get what you mean here 👀

2021-11-25 12:02 UTC, gmourier commented
> > we are sending a payload that is supposed to represent an API Key resource to the API
> 
> @gmourier I don’t get what you mean here 👀

It's just that for me the term request may not be clear between "making a request to retrieve information from an API" and "the purely technical fact to describe an HTTP communication".

To clarify here that we don't ask the API for information but we send it information but it is still a request.

It may not make much sense and may not matter much. Feel free to ignore it 😀  Request is probably very understandable for most people.

2021-12-01 11:06 UTC, guimachiavelli requested changes
I do agree with @gmourier's reasoning: while we are **requesting** the server to do something with an API Key, I think it is correct to emphasise the error is in the values given in our request.

2021-12-06 16:41 UTC, gmourier approved these changes
LGTM 📦

2021-12-20 15:37 UTC, guimachiavelli requested changes

2021-12-20 15:37 UTC, guimachiavelli commented on errors.yaml
> +    description: "The `description` field for the provided API key resource is invalid. It should either be a string or be set to`null`."
```suggestion
    description: "The `description` field for the provided API key resource is invalid. It should either be a string or `null`." 
```

2021-12-21 11:56 UTC, guimachiavelli approved these changes
LGTM 🐚

2021-12-23 12:54 UTC, guimachiavelli commented
bors merge

2021-12-23 12:56 UTC, merged