update known_limitations.md
meilisearch/documentation pull request #1468
Opened 2022-02-22 08:03 UTC by maryamsulemani97

closes #1415

2022-02-24 13:00 UTC, dichotommy reviewed
This looks fine to me. Maybe at the end of the explanation, we could add a brief sentence and/or example on what constitutes an `OR` filter, since an `OR` filter in array syntax might not be immediately recognizable for users.

I'm unsure of the use of the word "concatenated" here. I think "Maximum filter depth" would be a much clearer title for the section, but maybe that's just me.

2022-02-24 13:55 UTC, dichotommy requested changes

2022-02-24 13:55 UTC, dichotommy commented on learn/advanced/known_limitations.md
> +### Example
```suggestion
#### Example
```

2022-02-24 13:55 UTC, dichotommy commented on learn/advanced/known_limitations.md
> +If you tried filtering what users have access to a certain index using either of the following queries, they will not work:
```suggestion
The following filter expressions will cause search queries to fail:
```

2022-02-28 10:45 UTC, dichotommy approved these changes
LGTM! 🤿

2022-03-02 11:30 UTC, guimachiavelli commented on learn/advanced/known_limitations.md
> +```
Perhaps making this a json code block would improve reading slightly?

2022-03-03 16:29 UTC, Kerollmops requested changes
Apart from a  possible highlighting problem, it looks good to me.

2022-03-03 16:29 UTC, Kerollmops commented on learn/advanced/known_limitations.md
> +```json
```suggestion
```sql
```

2022-03-03 16:54 UTC, merged