Add Deploy on Koyeb guide
meilisearch/documentation pull request #1508
Opened 2022-03-08 11:11 UTC by edouardb

Hi there 👋,

Added a new guide to deploy Meilisearch on Koyeb.

2022-03-16 17:28 UTC, dichotommy requested changes
Hi @edouardb , thanks for your PR! 👋🏻 

We are concerned that your "Deploy to Koyeb" button may not be visible in dark mode, which was recently added to our site. Could you pull the latest changes from master and have a look?

2022-03-16 17:28 UTC, dichotommy commented on learn/cookbooks/koyeb.md
> +This guide explains how to deploy a ready-to-use Meilisearch service on Koyeb.
```suggestion
This guide explains how to deploy a ready-to-use Meilisearch instance on Koyeb.
```

2022-03-16 17:28 UTC, dichotommy commented on learn/cookbooks/koyeb.md
> +The fastest way to deploy Meilisearch on Koyeb is to use the **Deploy to Koyeb** button to deploy. It allows you to have your Meilisearch instance running with minimal configuration.
```suggestion
The fastest way to deploy Meilisearch on Koyeb is to use the **Deploy to Koyeb** button.
```

2022-03-16 17:28 UTC, dichotommy commented on learn/cookbooks/koyeb.md
> +### Test Meilisearch.
```suggestion
### Test Meilisearch
```

2022-03-16 17:28 UTC, dichotommy commented on learn/cookbooks/koyeb.md
> +Copy the public URL (e.g. `https://meili-myorg.koyeb.app`) from the [Koyeb control panel](https://app.koyeb.com) and paste it your browser.
```suggestion
Copy the public URL (e.g. `https://meili-myorg.koyeb.app`) from the [Koyeb control panel](https://app.koyeb.com) and paste it in your browser.
```

2022-03-16 17:28 UTC, dichotommy commented on learn/cookbooks/koyeb.md
> +You land on the MeiliSearch dashboard, where you are asked to authenticate using your master key.
```suggestion
You should land on the Meilisearch [search preview](/learn/what_is_meilisearch/search_preview.md), where you are asked to enter your master key.
```

2022-03-16 17:28 UTC, dichotommy commented on learn/cookbooks/koyeb.md
> +You are now ready to create your first index!
```suggestion
You are now ready to [create your first index](/learn/getting_started/quick_start.md)!
```

2022-03-21 16:52 UTC, dichotommy commented on index.md
> +- [Deploy Meilisearch on Koyeb](/learn/cookbooks/koyeb.md)
Hi @edouardb ! Do you think you could also remove this line when you update this PR?

The deploy links on our homepage are only intended to cover the top 3 or 4 industry-standard cloud providers. Adding Koyeb to that list might mean adding others in the future, and that could make our homepage very crowded. I hope you understand—your guide will still be accessible from the sidebar in the Learn section of the site.

Thank you very much!

```suggestion
```

2022-03-22 09:11 UTC, edouardb commented
> Hi @edouardb , thanks for your PR! 😄
> 
> We are concerned that your "Deploy to Koyeb" button may not be visible in dark mode, which was recently added to our site. Could you pull the latest changes from master and have a look?

Hi @dichotommy,

Thanks for the review!
I just checked the look of the button, it seems to be ok 👍 

<img width="793" alt="Screen Shot 2022-03-22 at 10 11 01 AM" src="https://user-images.githubusercontent.com/2520463/159446173-184d114d-3172-4cdb-a1fe-06c27aecbea7.png">

2022-03-23 09:30 UTC, merged