Primary key guide
meilisearch/documentation pull request #1544
Opened 2022-03-23 12:28 UTC by maryamsulemani97

1. I'm not sure if "Core concepts" is the right place for this guide. Any suggestions are welcome
2. Did I miss any other errors? I only mentioned the ones in https://github.com/meilisearch/documentation/issues/233

2022-03-23 13:46 UTC, dichotommy requested changes
I think this is a good start. Bringing this information onto its own page is a huge improvement over what we have currently. The next step is to improve the explanation of the primary key to make it less technical. Take the beginning for example:

> The primary key is a mandatory attribute linked to a unique value, the [document id](https://deploy-preview-1544--dreamy-wiles-8fd85b.netlify.app/learn/core_concepts/documents.html#document-id). It is part of the [primary field](https://deploy-preview-1544--dreamy-wiles-8fd85b.netlify.app/learn/core_concepts/documents.html#primary-field).
> 
> Each index recognizes only one primary key attribute. Once a primary key has been set for an index, it cannot be changed anymore. If no primary key is found in one document, none of the documents will be stored. The primary key ensures that there are no identical documents in the same index.

The language here is overly technical and dense with a lot of terminology right off the bat, and the second paragraph is basically a list of unrelated facts about primary keys. This doesn't really align with the idea of "core concepts". The explanation should start conceptual before getting more specific and technical.

Also, there's still a decent amount of content in the "primary field" section of the documents guide. Once we're sure that this information has been thoroughly copied over to the primary key guide, I would like to delete the content of this section entirely and basically replace it with a single sentence or two linking to the primary key guide.

Also—mentioning this here because it appears multiple times in both guides—it's a bit confusing to say:

> "The primary key can only be of type integer or string, composed of alphanumeric characters a-z A-Z 0-9, hyphens -, and underscores _."

This is true of the **value of the primary key** (what we currently call the document ID). These rules are common for unique IDs. However the primary key itself—what we could call the attribute of the field—can be any valid string (AFAIK). Example:

```
"Th!s i$ a \"valid\" primary key.": "this-is-a-valid-document-id"
"???": 123456
"'These are also valid primary keys ^'": "number-42_69_420"
```

Maybe I'm being overly precise here, but to me it's an important distinction 😅

2022-04-06 16:10 UTC, guimachiavelli requested changes
I think this is getting closer, but requires more polishing—mostly because the content of the original guides was in dire need of a review.

2022-04-06 16:10 UTC, guimachiavelli commented on learn/core_concepts/the_primary_key.md
> +
```suggestion

Once a primary key has been explicitly set for an index, it cannot be changed. 

```

2022-04-06 16:10 UTC, guimachiavelli commented on learn/core_concepts/the_primary_key.md
> +If no corresponding attribute is found, the index will have no known primary key, and therefore, **no documents will be added**.
```suggestion
If Meilisearch cannot find a suitable attribute, the document addition process will be interrupted and no documents will be added to your index.
```

2022-04-07 11:55 UTC, guimachiavelli approved these changes
Two minor text edits, but LGTM 🧚‍♂️

2022-04-07 11:55 UTC, guimachiavelli commented on learn/core_concepts/primary_key.md
> +Suppose we have a dataset containing several books. Each document contains several fields with data on the book's `author`, `title`, and `price`. More importantly, each document contains a **primary
```suggestion
Suppose we have a dataset containing several books. Each document contains a number fields with data on the book's `author`, `title`, and `price`. More importantly, each document contains a **primary field** indicating the books'  **primary key** `id` and a **document id**.
```

2022-04-07 11:55 UTC, guimachiavelli commented on learn/core_concepts/primary_key.md
> +### Example:
```suggestion
### Example
```

2022-04-07 15:09 UTC, guimachiavelli commented
I'm not sure I like "The primary key" as the page title, but if we can't think of anything else…I guess it's ok? 🤷 

If we do go with that, let's only change the page title, but keep the file name without the article.

2022-04-13 13:02 UTC, dichotommy requested changes
Great work 👏🏻 🥳 Once these comments have been addressed and merge conflicts have been fixed, I think this is ready to merge 🚀

2022-04-13 19:06 UTC, maryamsulemani97 commented on learn/core_concepts/primary_key.md
> +
I tried, lmk what you think

2022-04-13 19:10 UTC, maryamsulemani97 commented on learn/core_concepts/primary_key.md
> +To change the primary key of an index that already contains documents, you must [delete all documents](/reference/api/documents.md#delete-all-documents) from that index, [change the primary key](/ref
Is it a good idea to have a link for each step?

2022-04-20 12:05 UTC, dichotommy requested changes
Requesting some small final changes 🏄🏻

2022-04-20 12:05 UTC, dichotommy commented on learn/core_concepts/primary_key.md
> +The document id must be an integer or a string. If the id is a string, it can only contain alphanumeric characters (`a-z`, `A-Z`, `0-9`), hyphens (`-`), and underscores (`_`).
Could you switch this paragraph and the one on line 76?

2022-04-20 12:05 UTC, dichotommy commented on .code-samples.meilisearch.yaml
> +primary_field_guide_update_document_primary_key: |
```suggestion
primary_field_guide_update_primary_key: |
```

2022-04-26 16:06 UTC, dichotommy approved these changes
LGTM! Awesome work on this 👏🏻 🧱

2022-04-26 16:27 UTC, maryamsulemani97 commented
bors merge

2022-04-26 16:29 UTC, merged