primary key can be changed if index is empty
meilisearch/documentation pull request #1597
Opened 2022-04-13 19:58 UTC by maryamsulemani97

closes #1574

2022-04-14 16:19 UTC, guimachiavelli commented on reference/api/indexes.md
> +You can update the primary key of an empty index. If your index contains documents, you will need to delete all of them first, then change the primary key, and add them again.
At first I just wanted to separate empty/non-empty cases, but then the editing bug got me. Is this better?

```suggestion
You can freely update the primary key of an empty index.

You can also change the primary key of an index that already contains documents. To do that, you must first delete all documents in that index. You must then change the primary key, and finally index your dataset again.
```

2022-04-26 15:40 UTC, dichotommy requested changes

2022-04-26 15:40 UTC, dichotommy commented on reference/api/indexes.md
> +You can freely update the primary key of an empty index.
```suggestion
You can freely update the primary key of an index as long as it contains no documents.
```

2022-04-26 15:40 UTC, dichotommy commented on reference/api/indexes.md
> +You can also change the primary key of an index that already contains documents. To do that, you must first delete all documents in that index. You must then change the primary key, and finally index
```suggestion
To change the primary key of an index that already contains documents, you must first delete all documents in that index. You may then change the primary key and, finally, index your dataset again.
```

2022-04-26 15:40 UTC, dichotommy commented on reference/api/indexes.md
>  If a primary key wasn't explicitly chosen during index creation, you can use this route to configure it. If you are unsure whether an index's primary key has already been configured, you can use the
```suggestion
```

2022-04-28 16:20 UTC, dichotommy approved these changes
LGTM! 🧞

2022-04-28 16:22 UTC, maryamsulemani97 commented
bors merge

2022-04-28 16:23 UTC, merged