Update the document structure to explicit the expected content-type
meilisearch/documentation pull request #1641
Opened 2022-05-18 13:32 UTC by irevoire

I was wanted to send a jsonlines file to meilisearch and noticed three things;
1. We never wrote the term `jsonlines` anywhere while it’s more commonly used than `ndjson`. So the search bar was returning nothing. Maybe we should also create a synonym that binds `jsonlines` to `ndjson`.
2. The example was wrong; as explained in the documentation, each JSON object should be on ONE line and thus can’t contain any newline.
3. We never tell the content type of each accepted type. So even once I found my answer, I still had to look up on google which header I was supposed to send to meilisearch to make it accept my document

2022-05-18 13:40 UTC, maryamsulemani97 requested changes
Thanks for this @irevoire! 🙏
I suggested a few minor changes

2022-05-18 13:40 UTC, maryamsulemani97 commented on learn/core_concepts/documents.md
> +Meilisearch will expect JSON documents when it receive the `application/json` content-type header.
```suggestion

Meilisearch will only accept JSON documents when it receives the `application/json` content-type header.
```

2022-05-18 13:40 UTC, maryamsulemani97 commented on learn/core_concepts/documents.md
> +Meilisearch will expect NDJSON documents when it receive the `application/x-ndjson` content-type header.
```suggestion

Meilisearch will only accept NDJSON documents when it receives the `application/x-ndjson` content-type header.
```

2022-05-18 13:40 UTC, maryamsulemani97 commented on learn/core_concepts/documents.md
> +Meilisearch will expect NDJSON documents when it receive the `text/csv` content-type header.
```suggestion

Meilisearch will only accept NDJSON documents when it receives the `text/csv` content-type header.
```

2022-05-23 11:39 UTC, irevoire commented
Hey @maryamsulemani97 sorry for the delay and thanks for the review, I applied your changes 👍

2022-05-23 11:45 UTC, maryamsulemani97 requested changes
Sorry I missed this one

2022-05-23 11:45 UTC, maryamsulemani97 commented on learn/core_concepts/documents.md
> +Meilisearch will only accept NDJSON documents when it receives the `text/csv` content-type header.
```suggestion
Meilisearch will only accept CSV documents when it receives the `text/csv` content-type header.
```

2022-05-30 12:36 UTC, maryamsulemani97 approved these changes
bors merge

2022-05-30 12:37 UTC, merged