v0.28: Changes to /documents
meilisearch/documentation pull request #1736
Opened 2022-06-16 11:58 UTC by guimachiavelli

Closes #1700

2022-06-16 16:24 UTC, curquiza requested changes
According to [the spec](https://github.com/meilisearch/specifications/pull/143/files), the `fields` parameter is now also available for the `GET /indexes/:uid/documents/:document_uid` route.

2022-06-20 10:16 UTC, maryamsulemani97 reviewed
Looks good! 🦋 
A few suggestions:

- Update `learn/getting_started/algolia_migration.md` line 193: `displayedAttributes` setting does not impact the displayed fields returned
- I think we should update the `get_documents_1` code sample to show how to use the `fields` parameter 
- Add to note that `fields` values are case-sensitive.

2022-06-22 14:17 UTC, guimachiavelli commented
@maryamsulemani97: thanks for the suggestions. I agree with the second and third, but unless I'm mistaken the `attributesToRetrieve` mentioned in the line you indicated refers to the search parameter `attributesToRetrieve`, not `/documents`'s `fields`.

2022-06-22 15:56 UTC, curquiza approved these changes
🤘

2022-06-23 06:38 UTC, maryamsulemani97 commented
>unless I'm mistaken the attributesToRetrieve mentioned in the line you indicated refers to the search parameter attributesToRetrieve, not /documents's fields.

Two rows use `attributesToRetrieve`, lines 182 and 193. I'm assuming 182 refers to the search parameter

2022-06-29 13:08 UTC, guimachiavelli commented on reference/api/documents.md
> +  "total": 50134
```suggestion
  "total": 500134
```

2022-06-29 13:26 UTC, guimachiavelli commented
@maryamsulemani97: hmmmm…I'm not sure why it's there two times—could be an error, or that Algolia does not distinguish between things we do (and thus need two separate names). In any case, the line introducing the table reads (emphasis mine):

> The below table compares Algolia's API parameters with the equivalent **Meilisearch setting or search parameter**.

It explicitly states that this concerns settings and search parameters while `fields` is only concerned with the documents route. The main goal of this update seems to be to further distance `/documents` from `/search`— to the point that `fields` is now completely independent from `displayedAttributes`.

So I still think that, since the table is about index settings and search parameters, it should not be affected by changes to the /documents route.

2022-06-29 13:37 UTC, maryamsulemani97 approved these changes
🥷

2022-06-30 11:13 UTC, merged