Clarify interactions between `maxTotalHits` and `offset`
meilisearch/documentation pull request #1798
Opened 2022-08-03 16:04 UTC by guimachiavelli

Closes #1784

2022-08-08 12:25 UTC, dichotommy requested changes

2022-08-08 12:25 UTC, dichotommy commented on learn/advanced/known_limitations.md
> +**Explanation:** Meilisearch limits the maximum amount of returned search results to protect your database from malicious scraping. You may change this by using the `maxTotalHits` property of the [pa
```suggestion
**Explanation:** Meilisearch limits the total number of returned search results to protect your database from malicious scraping. There is no way to access search results past this limit, but you _can_ change it using the `maxTotalHits` property of the [pagination index settings](/reference/api/pagination.md#maxtotalhits).
```

2022-08-09 14:15 UTC, guimachiavelli commented on reference/api/search.md
>  :::
```suggestion
:::

::: warning
A search query cannot return more results than configured in [`maxTotalHits`](/reference/api/pagination.md#update-pagination-settings), even if the value of `limit` is greater than the value of `maxTotalHits`.
:::
```

2022-08-10 12:02 UTC, dichotommy commented on reference/api/search.md
> +You can paginate search results by making queries combining both `offset` and `limit`.
```suggestion
You can [paginate search results](/learn/advanced/pagination.md) by making queries combining both `offset` and `limit`.
```

2022-08-11 09:45 UTC, maryamsulemani97 approved these changes
👾

2022-08-11 17:49 UTC, merged