update 101: add faceting and pagination
meilisearch/documentation pull request #1833
Opened 2022-08-22 12:19 UTC by maryamsulemani97

closes #1717

2022-08-23 11:56 UTC, dichotommy requested changes
Requested a few changes to make the content more clear for beginners.

Observation: the `faceting` and `pagination` settings do not really help users fine-tune their search results or relevancy. Although this guide has thus far been comprehensive in how it presents the different settings, it may not make sense to continue doing that in the future.

2022-08-23 11:56 UTC, dichotommy commented on learn/getting_started/customizing_relevancy.md
> +Now, you won't be able to access search results beyond 500.
```suggestion
Now, users won't be able to access search results beyond 500.
```

2022-08-23 11:56 UTC, dichotommy commented on learn/getting_started/customizing_relevancy.md
> +
```suggestion

When creating a faceted search interface, it is helpful to display how results are distributed between the different categories. For example, a user might want to know how many of their results have a `"genre"` of `"comedy"` and how many have a `"genre"` of `"horror"`. Meilisearch supports this with [the `facets` search parameter](/reference/api/search.md#facets).

```

2022-08-23 11:56 UTC, dichotommy commented on learn/getting_started/customizing_relevancy.md
> +You can configure the maximum number of facet values returned for each facet.
```suggestion
Using the faceting settings, you can configure the maximum number of facet values returned for each facet.
```

2022-08-23 11:56 UTC, dichotommy commented on learn/getting_started/customizing_relevancy.md
> +Suppose a query's search results for the `genres` facet contains: `Action`, `Adventure`,`Science Fiction`, and `Comedy`. The following code sample will only return `Action` and `Adventure` in the res
```suggestion
Suppose your results contain the following values for the `genres` facet: `Action`, `Adventure`, `Science Fiction`, and `Comedy`. After running the below code sample, you would only see how results are distributed between the `Action` and `Adventure` genres.
```

2022-08-23 12:05 UTC, maryamsulemani97 commented on learn/getting_started/customizing_relevancy.md
> +When creating a faceted search interface, it is helpful to display how results are distributed between the different categories. For example, a user might want to know how many of their results have
```suggestion
When creating a faceted search interface, it is helpful to display how results are distributed between the different categories. For example, a user might want to know how many of their results have a `genre` of `comedy` and how many have a `genre` of `horror`. Meilisearch supports this with [the `facets` search parameter](/reference/api/search.md#facets).
```

2022-08-24 13:48 UTC, dichotommy approved these changes
LGTM 🙆🏻

2022-08-24 13:57 UTC, maryamsulemani97 commented
bors merge

2022-08-24 13:59 UTC, merged