update aws
meilisearch/documentation pull request #1885
Opened 2022-09-19 08:19 UTC by maryamsulemani97

This PR updates `learn/cookbooks/aws.md`

part of https://github.com/meilisearch/documentation/issues/1719

2022-09-19 16:09 UTC, guimachiavelli requested changes
Added a minor comment. If you think it's a bad idea, you mark it as resolved and re-request the review ☺️

2022-09-19 16:09 UTC, guimachiavelli commented on learn/cookbooks/aws.md
> +The "free tier" is sufficient for tests or prototypes, but not recommended for large datasets.
How about we leave it without quotes? This way we are referring to whatever free tier Amazon has and don't need to bother with its proper name.

2022-09-20 08:07 UTC, maryamsulemani97 commented on learn/cookbooks/aws.md
> +The "free tier" is sufficient for tests or prototypes, but not recommended for large datasets.
```suggestion
The free tier is sufficient for tests or prototypes, but not recommended for large datasets.
```

2022-09-21 11:36 UTC, guimachiavelli approved these changes
😶‍🌫️

2022-09-21 11:36 UTC, maryamsulemani97 commented
bors merge

2022-09-21 11:39 UTC, merged