v0.30: filtering and na n/infinity values
meilisearch/documentation pull request #2002
Opened 2022-11-10 14:05 UTC by maryamsulemani97

closes #2001

2022-11-10 14:10 UTC, Kerollmops approved these changes
Looks good to me!

I hope they understand that it will work perfectly and this is not a limitation on our side: it is not possible to write `NaN` or `inf` numbers in JSON, therefore it is impossible to store those as numbers in the database anyway! (ok you can use CSV but we handle them in the same way as in JSON).

2022-11-10 14:17 UTC, maryamsulemani97 commented
@Kerollmops 
Could you please share a link where this is explained:
>it is not possible to write `NaN` or `inf` numbers in JSON

I couldn't find anything 😕 
I can add it to clarify further that it's not a limitation on our side

2022-11-14 15:26 UTC, guimachiavelli commented on learn/advanced/filtering_and_faceted_search.md
> +Filters work with numeric and string values. Empty fields or fields containing an empty array will be ignored. Filtering with `inf` or `NaN` as numbers will throw an error as they are [not supported
I'm not sure about `inf`—it's fairly obvious, I guess, but are all users going to understand it means `Infinity`?  Perhaps we can use `Infinity` or even just "infinite numbers"?

2022-11-14 15:27 UTC, guimachiavelli requested changes
I think it's good, just wondering if `inf` is clear enough

2022-11-15 19:00 UTC, guimachiavelli approved these changes
🎤

2022-11-22 11:12 UTC, maryamsulemani97 commented
bors merge

2022-11-22 17:36 UTC, maryamsulemani97 commented
bors merge

2022-11-22 17:39 UTC, merged