replace ie and eg with written out forms
meilisearch/documentation pull request #2037
Opened 2022-12-09 11:32 UTC by sixhobbits

# Pull Request

## Related issue
* Fixes #1974 
* does not include vale rules, but replaces existing occurrences

## What does this PR do?
* replaces i.e. and e.g. with their written out forms as not everyone understands Latin abbreviations.

## PR checklist
Please check if your PR fulfills the following requirements:
- [ x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ x] Have you read the contributing guidelines?
- [ x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-12-12 13:55 UTC, maryamsulemani97 requested changes
Hi @sixhobbits 👋 
Thank you for your PR! I made some minor changes as `that is` and `for example` didn't sound right in some sentences. We should have clarified that in the [issue](https://github.com/meilisearch/documentation/issues/1974) 🙏 
Please let me know if you have any questions.

Thanks!

2022-12-12 13:55 UTC, maryamsulemani97 commented on learn/what_is_meilisearch/comparison_to_alternatives.md
> +Algolia is a company providing a search engine on a SaaS model. Its software is closed source. In its early stages, Algolia offered mobile search engines that could be embedded in apps, facing the ch
```suggestion
Algolia is a company providing a search engine on a SaaS model. Its software is closed source. In its early stages, Algolia offered mobile search engines that could be embedded in apps, facing the challenge of implementing the search algorithms from scratch. From the very beginning, the decision was made to build a search engine directly dedicated to the end-users, specifically, implementing search within mobile apps or websites.
```

2022-12-12 14:29 UTC, sixhobbits commented
thanks @maryamsulemani97 and @dichotommy - glad this one was useful. Requested changes have been committed. 

at Ritza.co we love helping companies extend and improve their docs, so just shout if we can ever be of more help!

2022-12-13 07:50 UTC, maryamsulemani97 approved these changes
Thanks again @sixhobbits!

bors merge

2022-12-13 07:51 UTC, merged