Remove`learn/configuration/settings.md`
meilisearch/documentation pull request #2044
Opened 2022-12-13 11:42 UTC by maryamsulemani97

closes #1614

2022-12-20 14:26 UTC, dichotommy requested changes
I really like the addition of the developer-friendly syntax to the settings API reference. I think it adds a lot in terms of drawing the reader's eye.

2022-12-20 14:26 UTC, dichotommy commented on learn/configuration/instance_options.md
> +These startup options affect your entire Meilisearch instance, not just a single index. For settings that affect search within a single index, see [index settings](/reference/api/settings.md).
I think it makes more sense to link to the overview table here, since they are in the same site section (configuration).

2022-12-20 14:26 UTC, dichotommy commented on learn/core_concepts/documents.md
> +With [ranking rules](/learn/core_concepts/relevancy.md#ranking-rules), you can decide what fields are more relevant than others. For example, you may decide recent movies should be more relevant than
Did not think the link was adding anything here—distracting, if anything—so replaced it with a segue to the next section.

Also, not the right PR to fix this... but this is a bad example! Making recent movies more relevant than older ones is an example of sorting on a single field. "Deciding which fields are more relevant than others," in the first sentence, alludes to attribute ranking order.

I may ask you to review this guide next week @maryamsulemani97 .

```suggestion
With [ranking rules](/learn/core_concepts/relevancy.md#ranking-rules), you can decide which fields are more relevant than others. For example, you may decide recent movies should be more relevant than older ones. You can also designate certain fields as displayed or searchable.
```

2022-12-20 14:26 UTC, dichotommy commented on learn/getting_started/algolia_migration.md
> +To customize your index settings, we recommend following [this guide](/reference/api/settings.md). To learn more about the differences between settings in Algolia and Meilisearch, read on.
API reference ≠ a guide, replace with link to settings section of index core concepts page.

In general, when linking from the getting started, we should prefer "explain"-y guides like those in the Learn section. There are of course exceptions, like the below example.

2022-12-20 14:26 UTC, dichotommy commented on learn/getting_started/filtering_and_sorting.md
> +To learn more about the `settings` object and how to configure it, refer to our [dedicated guide](/reference/api/settings.md).
"Dedicated guide" is not just go-to link text; it actually means something. We want our users to understand what they're clicking on.

```suggestion
To learn more about the `settings` object and how to configure it, check out the [API reference](/reference/api/settings.md).
```

2022-12-20 14:26 UTC, dichotommy commented on learn/security/tenant_tokens.md
> +Tenant tokens do not require you to configure any specific [instance options](/learn/configuration/instance_options.md) or [index settings](/reference/api/settings.md). They are also meant to be shor
```suggestion
Tenant tokens do not require you to configure any specific [instance options](/learn/configuration/instance_options.md) or [index settings](/learn/configuration/settings.md). They are also meant to be short-lived—Meilisearch does not store nor keeps track of generated tokens.
```

2022-12-20 14:26 UTC, dichotommy commented on reference/api/settings.md
> +We recommend that all your documents contain any attribute used in a custom ranking rule. For example, if you set the custom ranking rule `desc(year)`, make sure that all your documents contain the a
```suggestion
Make sure that any attribute used in a custom ranking rule is present in all of your documents. For example, if you set the custom ranking rule `desc(year)`, make sure that all your documents contain the attribute `year`.
```

2022-12-20 14:44 UTC, maryamsulemani97 commented on learn/configuration/instance_options.md
> +These startup options affect your entire Meilisearch instance, not just a single index. For settings that affect search within a single index, see [index settings](/reference/api/settings.md).
```suggestion
These startup options affect your entire Meilisearch instance, not just a single index. For settings that affect search within a single index, see [index settings](/learn/configuration/settings.md).
```

2022-12-20 15:14 UTC, maryamsulemani97 commented on learn/getting_started/algolia_migration.md
> +To customize your index settings, we recommend following [this guide](/reference/api/settings.md). To learn more about the differences between settings in Algolia and Meilisearch, read on.
```suggestion
To customize your index settings, we recommend following [this guide](/learn/core_concepts/indexes.md#index-settings). To learn more about the differences between settings in Algolia and Meilisearch, read on.
```

2022-12-22 11:09 UTC, dichotommy approved these changes
🧘🏻

2022-12-22 11:28 UTC, maryamsulemani97 commented
bors merge

2022-12-22 11:30 UTC, merged