v1.0: New error type :`system`
meilisearch/documentation pull request #2106
Opened 2023-01-11 13:33 UTC by maryamsulemani97

closes #2082

2023-01-16 16:01 UTC, irevoire approved these changes
purfect thanks! 🐈

2023-01-19 15:01 UTC, guimachiavelli requested changes

2023-01-19 15:01 UTC, guimachiavelli commented on reference/errors/overview.md
> +| **`system`**          | This indicates your system has reached or exceeded its limit for disk size, index size, etc., or the database doesn't have read or write access. It is accompanied by the HTT
Can we rewrite this without using "etc"? Either we list all causes or state a general category ("This indicates your system has reached or exceeded its disk space usage limits)—"etc" is sort of in-between and leaves too much open for interpretation.

2023-01-24 15:03 UTC, guimachiavelli approved these changes
🥡

2023-02-02 16:48 UTC, guimachiavelli commented
bors merge

2023-02-02 16:51 UTC, merged