v1.0: Remove mentions of `--disable-auto-batching`
meilisearch/documentation pull request #2110
Opened 2023-01-16 10:54 UTC by guimachiavelli

Closes #2085

2023-01-18 08:31 UTC, loiclec approved these changes
Looks good, thank you :)

2023-01-18 13:26 UTC, maryamsulemani97 requested changes
Looks good!
Just need to delete:
- the "Auto-batching and task cancelation" section in `learn/core_concepts/documents.md`
- line 194 in `learn/getting_started/quick_start.md`.

2023-01-18 13:26 UTC, maryamsulemani97 commented on learn/core_concepts/documents.md
>  #### Auto-batching and task cancelation
We should delete this section as well

2023-01-23 08:03 UTC, maryamsulemani97 approved these changes
My bad, I read the title as "remove mentions of auto-batching". 🤦‍♀️

2023-01-23 08:39 UTC, loiclec reviewed
On line 206 of `quick_start.md`, we still say:

> Most database operations in Meilisearch are [asynchronous](/learn/advanced/asynchronous_operations.md). This means that rather than being processed instantly, **API requests are added to a queue and processed one at a time**.

which I think is partly wrong, and may be confusing because of the previous paragraph that says:

> Meilisearch combines consecutive document requests into a single batch and processes them together.

Some API requests (index and task operations mostly) are added to a queue and processed "one at a time" **conceptually**. However, because of auto-batching, they are not **actually** processed one at a time. For example, if someone sends:
- (1) ten separate document additions
- (2) one settings update
- (3) a deletion of all the index's documents
- (4) another 15 document addition requests
- (5) another settings update 

Then meilisearch will (or at least could, I forgot the details in this specific case):
- (1+3) clear all the documents
- (2+5) change the settings
- (4) add all the documents from the 15 requests

**all at once.**

Therefore, I think it is safer to simply say that the API requests are added to a queue and processed later, without specifying how they are processed exactly.

2023-01-25 11:14 UTC, loiclec approved these changes
thanks! :)

2023-02-02 16:52 UTC, guimachiavelli commented
bors merge

2023-02-02 16:55 UTC, merged