v1.0: accepted os versions to run the Meilisearch binary
meilisearch/documentation pull request #2112
Opened 2023-01-16 13:24 UTC by maryamsulemani97

closes #2066

2023-01-19 10:26 UTC, curquiza reviewed
Thanks @maryamsulemani97!

2023-01-19 10:26 UTC, curquiza commented on learn/getting_started/supported_os.md
> +Any operating system or version not listed on this page does not mean Meilisearch won't work with it at all, we just don't guarantee it.
```suggestion
Any operating system or version not listed on this page does not mean Meilisearch won't work with it at all, we just don't guarantee it through our test suite.
```

2023-01-19 10:26 UTC, curquiza commented on learn/getting_started/quick_start.md
> +
Also docker is a good alternative 🐳

2023-01-19 10:26 UTC, curquiza commented on learn/getting_started/supported_os.md
> +If the provided binaries don't work for you, we recommend compiling Meilisearch from the source files. If the compilation fails, Meilisearch is not compatible with your machine.
And docker?

2023-01-19 10:26 UTC, curquiza commented on learn/getting_started/supported_os.md
> +The Meilisearch binary works on all Linux distributions with `amd64/x86_64` or `aarch64/arm64` architecture using glibc 2.27 and later.
Maybe give the command to know the glibs version (I put in the engine team issue)?

2023-01-19 10:26 UTC, curquiza commented on learn/getting_started/supported_os.md
> +Please ensure your operating system is listed on this page before installing the Meilisearch binary. Refer to the [changelog](https://github.com/meilisearch/MeiliSearch/releases) for more information
Maybe give link about how to install meilisearch binaries?

2023-01-19 10:34 UTC, davelarkan commented on learn/getting_started/quick_start.md
> +
I feel like there could be more mention of the Cloud in the quick start but it's probably something that requires more thought than just mentioning it in the `Supported operating systems` section.

For example, just above we say 
> We'll start with downloading and installing Meilisearch. You have the option to install Meilisearch locally or deploy it over a cloud service.

Which doesn't mention _our_ cloud service as an option.

Now that we have a free tier plan for testing Meilisearch we could consider Meilisearch Cloud as the fastest way to get started. And so perhaps the "Getting Started" area of the "Quick start" could have more of a cloud focus and much of the rest of this page could be moved to a separate "Installing and running Meilisearch" section.

That's quite a big change though and might not be something we feel is right strategically. I'm happy to hear what others think.

2023-01-19 10:34 UTC, maryamsulemani97 commented on .vale/styles/Vocab/word_list/accept.txt
> +glibc
This is used by [Vale](https://vale.sh/docs/vale-cli/overview/) (a prose linter). Vale checks for spelling as well. Some of the words we use in the docs don't exist in the dictionary. Adding them here means Vale doesn't show a warning for making a "typo".

2023-01-19 11:35 UTC, maryamsulemani97 commented on learn/getting_started/quick_start.md
> +
Hi! 👋 
We plan on restructuring the quick start after v1. The first step would be to have a [dedicated Installation page.](https://github.com/meilisearch/documentation/issues/2125) We will move this entire section along with the content in `supported_os.md` there. We do mention Docker in the Local installation section. 

Mentioning Meilisearch cloud is out of scope for this PR as it's dedicated to OS. But we will add it as part of restructuring the quick start.

2023-01-19 11:35 UTC, maryamsulemani97 commented on learn/getting_started/supported_os.md
> +If the provided binaries don't work for you, we recommend compiling Meilisearch from the source files. If the compilation fails, Meilisearch is not compatible with your machine.
Same as [previous comment](https://github.com/meilisearch/documentation/pull/2112#discussion_r1081140455)

2023-01-19 14:09 UTC, curquiza commented on learn/getting_started/quick_start.md
> +
Ok good to know! Thanks for the precision 😄

2023-01-19 14:10 UTC, curquiza approved these changes
Thanks @maryamsulemani97 😄

2023-01-24 14:59 UTC, guimachiavelli requested changes

2023-01-24 14:59 UTC, guimachiavelli commented on learn/getting_started/supported_os.md
> +If the provided [binaries](/learn/getting_started/quick_start.md#local-installation) don't work for you, we recommend compiling Meilisearch from the source files. If the compilation fails, Meilisearc
Besides the minor edits, I would also recommend moving this paragraph so it's after the supported OS list. This way users get the list ASAP, and then only need to read what to do if something goes wrong/their OS is not listed.

```suggestion
If the provided [binaries](/learn/getting_started/quick_start.md#local-installation) don't work for you, try building Meilisearch from source. If compilation fails, Meilisearch is not compatible with your machine.
```

2023-01-24 14:59 UTC, guimachiavelli commented on learn/getting_started/quick_start.md
> +The following operating systems are compatible with the Meilisearch binary:
Do users gain much from us specifying  compatibility with the binary? Can an OS be compatible with Meilisearch but incompatible with the binary?

```suggestion
The following operating systems are compatible with Meilisearch:
```

2023-01-24 14:59 UTC, guimachiavelli commented on learn/getting_started/supported_os.md
> +
I tried to integrate the info here on the first paragraph. The tone here is too informal for technical documentation, IMHO.

```suggestion
```

2023-01-25 12:43 UTC, guimachiavelli commented on learn/getting_started/supported_os.md
> +If the provided [binaries](/learn/getting_started/quick_start.md#local-installation) don't work for you, try building Meilisearch from source. If compilation fails, Meilisearch is not compatible with
Ok, I should have tested this on the preview before making my suggestion. Now it looks like it's part of the Windows instructions. I think the simplest solution is to return it to where it was, right below the first paragraph. Sorry 😅

2023-01-25 12:44 UTC, guimachiavelli requested changes
One final comment, rolling back on a previous suggestion. Should be good to go afterwards.

2023-01-26 11:06 UTC, guimachiavelli approved these changes
🆙

2023-02-02 16:57 UTC, guimachiavelli commented
bors merge

2023-02-02 16:59 UTC, merged