Make more accurate the Windows support
meilisearch/documentation pull request #2183
Opened 2023-02-21 17:27 UTC by curquiza

After discussing with @Kerollmops, we realized the current description of our OS support for Windows is not totally true (my bad). This PR fixes this

2023-02-23 17:59 UTC, guimachiavelli requested changes
Thanks for this! A few suggestions to make the text clearer.

2023-02-23 17:59 UTC, guimachiavelli commented on learn/getting_started/supported_os.md
> +Meilisearch binary works on Windows server 2022 and later.
```suggestion
The Meilisearch binary works on Windows Server 2022 and later.
```

2023-02-23 17:59 UTC, guimachiavelli commented on learn/getting_started/supported_os.md
> +Meilisearch test suite indeed runs on Windows server 2022, so we also expect Meilisearch binary to work on Windows OS 10 and later. However, you have to know Windows servers and Windows OS can be som
```suggestion
It is likely the Meilisearch binary also works with Windows OS 10 and later. However, due to the differences between Windows OS and Windows Server, Meilisearch does not officially support Windows OS.
```

2023-03-01 10:55 UTC, guimachiavelli approved these changes
🐱

2023-03-01 11:03 UTC, guimachiavelli commented
@curquiza: can I merge this or would you prefer to wait for @Kerollmops' review?

2023-03-01 11:30 UTC, maryamsulemani97 commented
bors merge

2023-03-01 11:30 UTC, maryamsulemani97 commented
bors cancel

2023-03-01 11:31 UTC, maryamsulemani97 commented
Sorry, I was supposed to merge another PR 🙏

2023-03-02 15:09 UTC, Kerollmops approved these changes
I loooove what you've wrote 🪟

2023-03-02 16:57 UTC, guimachiavelli commented
bors merge

2023-03-02 16:59 UTC, merged