Deployment actions & scraper migration
meilisearch/documentation pull request #2299
Opened 2023-04-06 00:17 UTC by justkahdri

# Pull Request
Add new workflow that triggers a deployment on staging (after launch it should point to `meilisearch.com/main`) and then runs the docs scraper.

2023-04-06 09:50 UTC, maryamsulemani97 commented on docs-scraper.config.json
> +          "anchor"
```suggestion
          "*"
```
We want to use the current docs search settings

2023-04-06 11:17 UTC, dichotommy requested changes
Please update the `MEILISEARCH_HOST_URL` and `MEILISEARCH_API_KEY` secret variables.

2023-04-06 15:43 UTC, guimachiavelli commented on docs-scraper.config.json
> +}
New line character after the last line to make github happy

```suggestion
}

```

2023-04-08 04:26 UTC, dichotommy approved these changes
LGTM!

2023-04-08 04:34 UTC, dichotommy commented on docs-scraper.config.json
> +  "index_uid": "new-docs-structure",
```suggestion
  "index_uid": "new-docs-staging",
```

2023-04-08 04:35 UTC, merged