Improve site organization + visibility: Features page
meilisearch/documentation pull request #2393
Opened 2023-05-02 08:31 UTC by maryamsulemani97

closes #2388

Removes the features page and moves content to `learn/what_is_meilisearch/overview.mdx`. 

### For reviewers
Is the list of features on `learn/what_is_meilisearch/overview.mdx` too long?

2023-05-08 12:50 UTC, guimachiavelli requested changes
Looks good, but there are two things we can improve:

- If I recall correctly, our style guides establish line items should not end in punctuation marks
- The text in the older bits is not great. Might be out of scope for the linked issue, but if you have the time it wouldn't hurt to polish them a bit. You might want to check out the meilisearch/meilisearch readme—there's a similar list there and I think we reviewed it more or less recently.

2023-05-10 13:47 UTC, guimachiavelli requested changes
I think we're almost done, but missing a certain consistency/uniformity between list items. The majority of descriptions begins with a verb—configure, manage, filter. Is it possible to have all following the same pattern?

2023-05-10 13:47 UTC, guimachiavelli commented on learn/what_is_meilisearch/overview.mdx
>  - **Highly customizable search and indexing**:
Huh, just noticed we don't have anything here, which clashes hard against every other feature having some descriptive text. We should add something so it's in line with the other items.

2023-05-25 09:53 UTC, dichotommy approved these changes
LGTM!

Gui is right of course about the phrasal consistency—would probably sound better if each feature bullet started with a verb—but does not seem a priority to do that right now.

For the redirect, I'm thinking straight to https://www.meilisearch.com/ . Sounds good?

2023-05-25 14:54 UTC, guimachiavelli approved these changes

2023-05-29 11:12 UTC, merged