Update `relevancy.mdx` to remove h3s from containers+add missing tab
meilisearch/documentation pull request #2456
Opened 2023-06-08 08:18 UTC by maryamsulemani97

1. This PR removes the following headings from containers:
![Screenshot 2023-06-07 at 16 35 38](https://github.com/meilisearch/documentation/assets/90181761/c26958e7-010b-4991-a04e-1b3e72355d12)
These headings appear in the sidebar when they shouldn't

2. Updates `Tabs.Container labels` to add "Exactness". The "Exactness" tab is currently missing from the container:
![Screenshot 2023-06-08 at 12 18 04](https://github.com/meilisearch/documentation/assets/90181761/748b5c5a-5473-4983-a7b5-c3ebcb35a680)

2023-06-08 14:53 UTC, guimachiavelli requested changes
Hmmmm…isn't the problem here that we're using `h3`s to tag headings that should be `h5`s?

Like, the way I read that section is:

```markdown
### Built-in rules
#### Words
#### Typo
[…]
#### Examples
##### Typo
##### Words
[etc]
```

- We have a section for "Built-in Rules" (h3)
- This section contains subsections for ranking rules (h4) and a final subsection for "Examples" (also h4)
- "Examples" itself contains subsections for each individual example  (h5)

2023-06-12 11:24 UTC, maryamsulemani97 commented
>"Examples" itself contains subsections for each individual example (h5)

"Examples" is a container with 4 tabs. We have an h3 for each of these tabs.

I replaced the h3s with h5s

2023-06-14 10:25 UTC, dichotommy commented
I'm going to contradict @guimachiavelli 's comment and say that you had it right the first time Maryam: these should not be headers, they should just be bold text. 

The problem is that headers and tabs do not play well together. Let's take `Words` as an example. If you try to navigate to `#words` anchor, either from the right-hand sidebar or by entering the link, it will not work. Either you will see the top of the page because the anchor was not found, or you will see the correct part of the page but the wrong tab (because `typo` tab is open by default).

2023-06-15 06:16 UTC, maryamsulemani97 commented
>The problem is that headers and tabs do not play well together. Let's take Words as an example. If you try to navigate to #words anchor, either from the right-hand sidebar or by entering the link, it will not work. Either you will see the top of the page because the anchor was not found, or you will see the correct part of the page but the wrong tab (because typo tab is open by default).

Reverted the H5s to bold

2023-06-20 17:33 UTC, guimachiavelli commented
I still disagree with @dichotommy. Headings are not necessarily links—they are semantic elements indicating relationship and information hierarchy. `h[number]` generating an anchor link is a UX thing we actively program for.

Using bold might solve the immediate visual issue, but at the cost of weakening the connection between e.g. "typo" and the content that comes after it.

As far as I know, `h5`s won't appear on the right-hand menu, so while users might still click on the heading and get the anchor link, the impact will be relatively limited. Because of that, I believe `h5`s are better and lead to sturdier data on the long run.

The ideal solution, in my opinion, would be to use `h5`s and commission basement to find a proper solution—such as not adding anchor links to headings inside tabs, or, even better, somehow detecting when a URI fragment is pointing to something in a hidden tab and display it.

2023-06-21 07:52 UTC, maryamsulemani97 commented on learn/core_concepts/relevancy.mdx
> +**Typo**
```suggestion
##### Typo
```

2023-06-21 13:11 UTC, maryamsulemani97 commented
Visually there isn't any difference between bold and h5:
![Screenshot 2023-06-21 at 11 59 47](https://github.com/meilisearch/documentation/assets/90181761/eb73ec4d-5c62-4aae-b4a9-1791f277ddbe)

![Screenshot 2023-06-21 at 11 51 10](https://github.com/meilisearch/documentation/assets/90181761/f4894f0b-449c-4b94-b20a-8ca3e730b179)

>Let's take Words as an example. If you try to navigate to #words anchor, either from the right-hand sidebar or by entering the link, it will not work. Either you will see the top of the page because the anchor was not found, or you will see the correct part of the page but the wrong tab (because typo tab is open by default).

You don't get anchor links by clicking on H5s in a container. Since users won't get anchor links, they can't use them so this won't be a problem. 

Something I didn't consider, but Gui brought up, is the scraper. Bold text is just like ordinary text (content) to it.

2023-06-21 13:11 UTC, maryamsulemani97 commented on learn/core_concepts/relevancy.mdx
> +**Proximity**
```suggestion
##### Proximity
```

2023-06-21 13:12 UTC, maryamsulemani97 commented on learn/core_concepts/relevancy.mdx
> +**Attribute**
```suggestion
##### Attribute
```

2023-06-21 13:12 UTC, maryamsulemani97 commented on learn/core_concepts/relevancy.mdx
> +**Exactness**
```suggestion
##### Exactness
```

2023-06-22 12:46 UTC, guimachiavelli approved these changes
🥼

2023-06-22 13:22 UTC, merged