Reduce containers
meilisearch/documentation pull request #2466
Opened 2023-06-15 16:04 UTC by maryamsulemani97

Part of https://github.com/meilisearch/documentation/issues/2377

This PR reduces containers from the `learn` section.

2023-06-22 12:55 UTC, guimachiavelli requested changes
Couple minor suggestions and we should be good to go.

2023-06-29 08:29 UTC, dichotommy requested changes

2023-06-29 08:29 UTC, dichotommy commented on learn/fine_tuning_results/faceted_search.mdx
> -<Capsule intent="note">
I would keep this container and make it a "tip". It's extra information that could be helpful.

2023-06-29 08:29 UTC, dichotommy commented on learn/fine_tuning_results/faceted_search.mdx
> +When using the `facets` parameter, Meilisearch results include a `facetStats` object. `facetStats` contains the lowest (`min`) and highest (`max`) numerical values across all documents in each facet.
```suggestion
When using the `facets` parameter, search results include a `facetStats` object. `facetStats` contains the lowest (`min`) and highest (`max`) numerical values across all documents in each facet. Only numeric values are considered; string values are ignored, even if the string contains a number.
```

2023-06-29 08:29 UTC, dichotommy commented on learn/index_settings/synonyms.mdx
>  When a multi-word phrase is considered the synonym of another word or phrase, the **exact search query will always take precedence over its synonym(s)**.
```suggestion
Multi-word synonyms follow a different set of rules than single-word synonyms:

- When a multi-word phrase is set as a synonym, **the exact search query will always take precedence over its multi-word synonym(s)**
- Meilisearch treats multi-word synonyms as [phrases](/reference/api/search#phrase-search-2)
- Multi-word synonyms are limited to a maximum of three words

```

2023-06-29 11:51 UTC, guimachiavelli requested changes
Do take a look at @dichotommy's requested changes and re-request my review once they're done.

2023-07-13 10:05 UTC, guimachiavelli approved these changes

2023-07-13 10:22 UTC, merged