Fix filter depth limitation
meilisearch/documentation pull request #2568
Opened 2023-09-20 14:35 UTC by curquiza

Following an internal discussion [here](https://meilisearch.slack.com/archives/C0557UPQHQA/p1695037338945139)

2023-09-20 14:59 UTC, irevoire commented on learn/inner_workings/known_limitations.mdx
> +id = 1 OR (id = 2 AND (id = 3 OR (id = 4 AND id = 5)))
```suggestion
# Here we have a depth of 4
id = 1 OR (id = 2 AND (id = 3 OR (id = 4 AND id = 5)))

# But here the depth is still 2
id = 1 OR (id = 2 AND id = 3) OR (id = 4 AND id = 5) OR id = 6
```

What do you think of adding another last example just to be sure no one thinks that mixing AND and OR *will automatically* increase the depth?

2023-09-20 15:32 UTC, irevoire submitted a review, later dismissed

2023-09-26 17:28 UTC, guimachiavelli requested changes

2023-09-26 17:28 UTC, guimachiavelli commented on learn/inner_workings/known_limitations.mdx
> +**Explanation:** Regarding filering, the depth increases when mixing and alterning `AND` and `OR` operators filters creating nested structures which can lead to a stack overflow.
```suggestion
**Explanation:** mixing and alternating `AND` and `OR` operators filters creates nested logic structures. Excessive nesting can lead to stack overflow.
```

2023-09-26 17:28 UTC, guimachiavelli commented on learn/inner_workings/known_limitations.mdx
> +The following filter with the chained `OR` operators corresponds to a depth of 1:
```suggestion
The following filter is composed of a number of filter expressions. Since these statements are all chained with `OR` operators, there is no nesting:
```

2023-09-26 17:28 UTC, guimachiavelli commented on learn/inner_workings/known_limitations.mdx
> +user = 1 OR user = 2 […] OR user = 10000
```suggestion
genre = "romance" OR genre = "horror" OR genre = "adventure"
```

2023-09-26 17:28 UTC, guimachiavelli commented on learn/inner_workings/known_limitations.mdx
> +We got the same behavior with chained `AND` operators: the depth is still 1.
````suggestion
Replacing `OR` with `AND` does not change the filter structure. The following filter's nesting level remains 1:

```sql
genre = "romance" AND genre = "horror" AND genre = "adventure"
```
````

2023-09-26 17:28 UTC, guimachiavelli commented on learn/inner_workings/known_limitations.mdx
> +```
````suggestion
Nesting only occurs when alternating `AND` and `OR` operators. The following example fetches documents that either belong only to `user` `1`, or belong to users `2` and `3`:

```sql
# AND is nested inside OR, creating a second level of nesting
user = 1 OR user = 2 AND user = 3
```

Adding parentheses can help visualizing nesting depth:

```sql
# Depth 2
user = 1 OR (user = 2 AND user = 3)

# Depth 4
user = 1 OR (user = 2 AND (user = 3 OR (user = 4 AND user = 5)))

# Though this filter is longer, its nesting depth is still 2
user = 1 OR (user = 2 AND user = 3) OR (user = 4 AND user = 5) OR user = 6
```
````

2023-09-27 11:52 UTC, irevoire approved these changes

2023-09-28 16:06 UTC, merged