Add link to RBAC blog post
meilisearch/documentation pull request #2576
Opened 2023-10-02 16:49 UTC by guimachiavelli

Closes #2505

2023-10-03 14:05 UTC, CaroFG requested changes

2023-10-03 14:05 UTC, CaroFG commented on learn/security/tenant_tokens.mdx
> +You can also use tenant tokens in role-based accrss control (RBAC) systems. Consult [How to implement RBAC with Meilisearch](https://blog.meilisearch.com/role-based-access-guide/) on Meilisearch's of
```suggestion
You can also use tenant tokens in role-based access control (RBAC) systems. Consult [How to implement RBAC with Meilisearch](https://blog.meilisearch.com/role-based-access-guide/) on Meilisearch's official blog for more information.
```

2023-10-04 15:18 UTC, guimachiavelli commented on learn/security/tenant_tokens.mdx
> +You can also use tenant tokens in role-based accrss control (RBAC) systems. Consult [How to implement RBAC with Meilisearch](https://blog.meilisearch.com/role-based-access-guide/) on Meilisearch's of
🤦 

thanks for spotting it!

2023-10-05 07:01 UTC, CaroFG approved these changes

2023-10-05 09:27 UTC, merged