Update railway.mdx to reference production-ready Railway template
meilisearch/documentation pull request #2578
Opened 2023-10-03 22:21 UTC by melissa-hale

# Pull Request

## Related issue
No open issue.  This change is being proposed because the template that is currently being deployed from the Deploy to Railway button on this page is not production ready - it does not have a volume attached meaning data will not be persisted between deploys, and the MEILI_ENV environment variable is set to development by default.

## What does this PR do?
Update railway.mdx to point to a template that provides a production-ready instance of Meilisearch.  This Railways template includes default environment variables are production-ready and a volume attached for persisted data.
This change also updates the content to reflect that Meilisearch search preview is only available if you set your environment variable to "development" instead of the default "production"

## PR checklist
Please check if your PR fulfills the following requirements:
- [ x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x ] Have you read the contributing guidelines?
- [x ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

Thank you!!

2023-10-09 16:53 UTC, guimachiavelli submitted a review, later dismissed
Hi, @melissa-hale! Thanks for this PR (and your very thorough explanation, which is very much appreciated)!

It looks pretty good to me. I made a few minor suggestions, but they are mostly to make it consistent with our internal style guide.

I'm also requesting a technical review from @brunoocasali, one of our devs, to ensure we didn't miss anything.

2023-10-09 17:07 UTC, brunoocasali requested changes
Hey, thanks a lot for bringing this up!

2023-10-11 18:16 UTC, melissa-hale commented on learn/deployment/railway.mdx
> +[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/new/template/meilisearch)
Hi @brunoocasali !  Thank you so much for the review.  We can certainly update the path there.  I'll report back once I get it fixed so you can test it out.

Regarding ownership - One of my counterparts here at Railway is the official owner of this particular template.  We are happy to collaborate on any updates/additions you all would like to see in the template!

2023-10-17 14:06 UTC, guimachiavelli commented
@brunoocasali, If I understand correctly, your final comment must be addressed outside the documentation and everything else is great as far as you're concerned. Is that correct? If so, may I merge the PR?

thanks!

2023-10-17 17:37 UTC, brunoocasali commented on learn/deployment/railway.mdx
> +[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/new/template/meilisearch)
Thanks for changing it @melissa-hale unfortunately I made a mistake, I don't know why I said you should change to /ms 🤔 

Could you please update it to follow the https://www.meilisearch.com/docs/learn/cookbooks/docker#run-meilisearch-with-docker which is `/meili_data` ?

I'm so sorry I mislead you 😢

2023-10-17 17:38 UTC, brunoocasali commented
Yes @guimachiavelli you can merge it, I just asked one more thing (to fix a induced error), but you could merge it anyway :)

2023-10-17 17:38 UTC, brunoocasali approved these changes

2023-10-18 15:29 UTC, merged