Add YAML description meta tags
meilisearch/documentation pull request #2582
Opened 2023-10-16 17:15 UTC by guimachiavelli

Fixes #2573

2023-10-17 16:54 UTC, guimachiavelli commented on learn/cookbooks/postman_collection.mdx
> +description: Postman is a platform that lets you create HTTP requests you can easily reuse and share with everyone. This how-to guide explains how to use Postman to help testing and debugging Meilise
```suggestion
description: This how-to guide explains how to use Postman when testing and debugging Meilisearch's API.
```

2023-10-17 16:55 UTC, guimachiavelli commented on learn/cookbooks/search_bar_for_docs.mdx
> +description: Use Meilisearch to index content in a text-heavy website. Covers installing Meilisarch, configuring a text scraper, and creating a simple front end.
```suggestion
description: Use Meilisearch to index content in a text-heavy website. Covers installing Meilisearch, configuring a text scraper, and creating a simple front end.
```

2023-10-17 16:56 UTC, guimachiavelli commented on learn/core_concepts/relevancy.mdx
> +description: Relevancy refers to the accuracy of search results. If search results tend to be appropriate, then they can be considered relevant.
```suggestion
description: Relevancy refers to the accuracy of search results. If search results tend to be appropriate for a given query, then they can be considered relevant.
```

2023-10-17 16:56 UTC, guimachiavelli commented on learn/data_backup/dumps.mdx
> +description: Dumps are data backups containing all data related to a Meilisearch instance. They are often useful when migrating to a new Meiliearch release.
```suggestion
description: Dumps are data backups containing all data related to a Meilisearch instance. They are often useful when migrating to a new Meilisearch release.
```

2023-10-17 16:56 UTC, guimachiavelli commented on learn/data_backup/snapshots_vs_dumps.mdx
> +description: "Meilisearch offers two types of backups: snapshots and dumps. Snapshots are mainly intended as a safeguard, while dumps are more useful when migrating Meilisearch."
```suggestion
description: "Meilisearch offers two types of backups: snapshots and dumps. Snapshots are mainly intended as a safeguard, while dumps are useful when migrating Meilisearch."
```

2023-10-17 16:57 UTC, guimachiavelli commented on learn/experimental/metrics.mdx
> +description: The /metrics endpoint is an experimental feature. It exposes data compatible with Prometheus and offers valuable insight into Meilisearch's behavior and performance.
```suggestion
description: The /metrics endpoint is an experimental feature. It exposes data compatible with Prometheus and offers insight into Meilisearch's behavior and performance.
```

2023-10-17 16:58 UTC, guimachiavelli commented on learn/experimental/overview.mdx
> +description: Activate and configure Meilisearch experimental features. Meilisearch's experimental features offer exciting new functionality that is still undergoing development.
```suggestion
description: Activate and configure Meilisearch experimental features. Meilisearch's experimental features offer exciting new functionality that is still in development.
```

2023-10-17 16:58 UTC, guimachiavelli commented on learn/experimental/ranking_rule_score_details.mdx
> +description: The --experimental-score-details flag offers in-depth data about how a query's ranking scores.
```suggestion
description: The --experimental-score-details flag offers in-depth data about a query's ranking scores.
```

2023-10-17 16:58 UTC, guimachiavelli commented on learn/experimental/reduce-indexing-memory-usage.mdx
> +description: The --experimental-reduce-indexing-memory-usage enables MDB_WRITEMAP, which might improve performance in some UNIX and UNIX-like setups.
```suggestion
description: The --experimental-reduce-indexing-memory-usage enables MDB_WRITEMAP, which can improve performance in some UNIX and UNIX-like setups.
```

2023-10-17 16:59 UTC, guimachiavelli commented on learn/fine_tuning_results/faceted_search.mdx
> +description: Faceted search interfaces are provide users with a quick way to narrow down search results by selecting categories relevant to their query.
```suggestion
description: Faceted search interfaces provide users with a quick way to narrow down search results by selecting categories relevant to their query.
```

2023-10-17 16:59 UTC, guimachiavelli commented on learn/fine_tuning_results/filtering.mdx
> +description: Filters allow your users to refine search results and are a fundamental element when creating faceted search interfaces.
```suggestion
description: Filters allow your users to refine search results. They can also be used when creating faceted search interfaces.
```

2023-10-17 17:00 UTC, guimachiavelli commented on learn/fine_tuning_results/working_with_dates.mdx
> +description: Learn about Meilisearch's approach to date and time values, how to index documents with chronological data, and how to sort and filter search results based on time.
```suggestion
description: Learn how to index documents with chronological data, and how to sort and filter search results based on time.
```

2023-10-17 17:02 UTC, guimachiavelli commented on learn/getting_started/installation.mdx
> +description: Use Meilisearch with Meilisearch Cloud, another cloud service, or install it locally.
```suggestion
description: Use Meilisearch with either Meilisearch Cloud, another cloud service, or install it locally.
```

2023-10-17 17:02 UTC, guimachiavelli commented on learn/index_settings/all_index_settings.mdx
> +description: Meilisearch has several index-specific settings to ensure maximum relevancy with many different datasets and use-cases.
```suggestion
description: Meilisearch has several index-specific settings to ensure maximum relevancy with different datasets and use-cases.
```

2023-10-17 17:06 UTC, guimachiavelli commented on learn/inner_workings/tokenization.mdx
> +description: Tokenization is the act of taking a sentence or phrase and splitting it into smaller units of language. It is a crucial process when indexing documents.
```suggestion
description: Tokenization is the process of taking a sentence or phrase and splitting it into smaller units of language. It is a crucial procedure when indexing documents.
```

2023-10-17 17:07 UTC, guimachiavelli commented on learn/update_and_migration/algolia_migration.mdx
> +description: This guide will take you step-by-step through the creation of a Node.js script to upload Algolia index data to Meilisearch.
```suggestion
description: This guide will take you step-by-step through the creation of a Node.js script to upload data indexed by Algolia to Meilisearch.
```

2023-10-17 17:08 UTC, guimachiavelli commented on learn/update_and_migration/versioning.mdx
> +description: This article describes the system behind Meilisearch's SDK and engine version numbering, as well as compatibility between different releases.
```suggestion
description: This article describes the system behind Meilisearch's SDK and engine version numbering and compatibility.
```

2023-10-17 17:09 UTC, guimachiavelli commented on reference/api/overview.mdx
> +description: Consult this page for an overview of how to query Meilisearch's API, which types of parameters it supports, and how it structures responses.
```suggestion
description: Consult this page for an overview of how to query Meilisearch's API, which types of parameters it supports, and how it structures its responses.
```

2023-10-18 08:23 UTC, qdequele commented
Hello @guimachiavelli it's great! Is it also possible to add the titles? I did it in my test PR. https://github.com/meilisearch/documentation/pull/2571/files

2023-10-18 08:24 UTC, qdequele requested changes
Hello @guimachiavelli it's great! Is it also possible to add the titles? I did it in my test PR. https://github.com/meilisearch/documentation/pull/2571/files

2023-10-19 11:57 UTC, guimachiavelli commented
Hi @qdequele! My plan is to address the titles programmatically, as the majority should really be `[Page's H1] — Meilisearch documentation`. So, for example, the page title for the cloud getting started would be `Getting started with Meilisearch Cloud — Meilisearch documentation`. I'm looking into how to do that, but I believe we might be able to skip basement.

2023-10-24 16:38 UTC, guimachiavelli commented
After some research, `<title>`s were not implemented in a way we can easily and safely customise. Skipping basement and doing it ourselves does not look like a good choice.

Taking in consideration the time it will take for basement to do this, though, I have manually edited the `<title>` for each documentation page. 

At a later date, once they're done with our current requests, we'll investigate how we can properly automate this.

2023-10-26 21:44 UTC, qdequele approved these changes
LGTM

2023-10-30 10:55 UTC, curquiza approved these changes

2023-10-30 10:57 UTC, merged