Add GHA to add a comment displaying preview information on each opened PR
meilisearch/documentation pull request #2603
Opened 2023-10-26 12:52 UTC by curquiza

2023-10-26 17:56 UTC, curquiza commented
@guimachiavelli the PR is finally ready for review. You can see with https://github.com/meilisearch/documentation/pull/2605 the automation is working and is only triggered once when the PR is opened

2023-10-30 10:40 UTC, guimachiavelli requested changes

2023-10-30 10:40 UTC, guimachiavelli commented on .github/workflows/preview-info.yml
> +          echo '⚠️ Accessible for internal Meili people only.' >> comment.txt
```suggestion
          echo '⚠️  Private link, only accessible to Meilisearch employees.' >> comment.txt
```

2023-10-30 10:40 UTC, guimachiavelli commented on .github/workflows/preview-info.yml
> +          echo "Go to this URL: https://website-git-deploy-preview-mei-16-meili.vercel.app/docs/branch%3A$CURRENT_BRANCH" >> comment.txt
Do we need to use the HTML entity for the colon (`:`)? I know browsers convert it anyway, but `:` will be easier to understand if someone has to revisit this action.

```suggestion
          echo "Go to this URL: https://website-git-deploy-preview-mei-16-meili.vercel.app/docs/branch:$CURRENT_BRANCH" >> comment.txt
```

2023-10-30 11:04 UTC, guimachiavelli approved these changes

2023-10-30 11:19 UTC, merged