Add notices about configuring Meilisync primary key
meilisearch/documentation pull request #2623
Opened 2023-11-06 16:13 UTC by Strift

# Pull Request

## Related issue
Fixes #2598 

## What does this PR do?
- Add a notice about the field to configure the primary key for meilisync

2023-11-09 14:47 UTC, guimachiavelli requested changes
Just a minor change so we're using proper heading elements. Only bold might become an accessibility issue since it is harder for screen readers to interpret a paragraph is a new subsection when we only use bold to mark up the heading.

Alternatively, you could try to create another `<Capsule>`, but not sure we want to have two of those so close to each other.

2023-11-09 14:47 UTC, guimachiavelli commented on learn/primary_db_sync/meilisync_mysql.mdx
> +**Primary key inference**
```suggestion
### Primary key inference
```

2023-11-09 14:47 UTC, guimachiavelli commented on learn/primary_db_sync/meilisync_postgresql.mdx
> +**Primary key inference**
```suggestion
### Primary key inference
```

2023-11-13 08:18 UTC, Strift commented
Thanks for the recommendation. Commited the suggested changes!

2023-11-13 16:28 UTC, Strift commented
I'm not aware of any reason to hold this so I would say "yes" :)

2023-11-14 09:16 UTC, merged