Change docs-searchbar.js description to deprecated
meilisearch/documentation pull request #2648
Opened 2023-12-09 15:12 UTC by PzaThief

# Pull Request

## Related issue

## What does this PR do?
- Change docs-searchbar.js description to deprecated following docs-searchbar.js repository

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-12-12 17:26 UTC, guimachiavelli requested changes
Hello @PzaThief, and thank you for taking the time to contribute to our repo.

I have discussed the deprecated docs-searchbar repo with the rest of team and we think it would be more useful to direct users to a maintained fork. This way they can continue moving forward with their research.

I made a suggestion on the PR. If you agree with our decision, please commit it and I'll merge this PR ASAP.

Thanks again!

2023-12-12 17:26 UTC, guimachiavelli commented on learn/what_is_meilisearch/sdks.mdx
> +- [docs-searchbar.js](https://github.com/meilisearch/docs-searchbar.js) (deprecated)
```suggestion
- [docs-searchbar.js](https://github.com/tauri-apps/meilisearch-docsearch)
```

2023-12-13 05:00 UTC, PzaThief commented
> Hello @PzaThief, and thank you for taking the time to contribute to our repo.
> 
> I have discussed the deprecated docs-searchbar repo with the rest of team and we think it would be more useful to direct users to a maintained fork. This way they can continue moving forward with their research.
> 
> I made a suggestion on the PR. If you agree with our decision, please commit it and I'll merge this PR ASAP.
> 
> Thanks again!

Thanks for your suggestion. I agree with your opinion so committed it.

2023-12-13 10:21 UTC, guimachiavelli approved these changes
Looks good to me! Thanks again, @PzaThief! ☺️

2023-12-13 10:21 UTC, merged