Add Laravel Scout guide
meilisearch/documentation pull request #2715
Opened 2024-02-13 12:10 UTC by Strift

# Pull Request

Solves #2713 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-02-19 16:11 UTC, guimachiavelli requested changes
A few minor changes, but looks good. Very concise and to the point. If you have the time, I think the only part that might need some extra work is the subsections of "Configuring the laravel scout driver".

2024-02-19 16:11 UTC, guimachiavelli commented on learn/cookbooks/laravel-scout.mdx
> +Read our [Meilisearch Cloud quick start](/learn/getting_started/cloud_quick_start?utm_campaign=laravel&utm_source=docs&utm_medium=laravel-scout-guide).
```suggestion
Read the [Meilisearch Cloud quick start](/learn/getting_started/cloud_quick_start?utm_campaign=laravel&utm_source=docs&utm_medium=laravel-scout-guide).
```

2024-02-19 16:11 UTC, guimachiavelli commented on learn/cookbooks/laravel-scout.mdx
> +This trait will use Laravel’s model observers to keep the data in your model in sync with Meilisearch.
Call me heartless. I removed your emoji.

More seriously, I think these two work better as a single paragraph so it reinforces the connection between "this trait" and the trait you're referring to.

```suggestion
With Scout installed and configured, add the `Laravel\Scout\Searchable` trait to your Eloquent models to make them searchable. This trait will use Laravel’s model observers to keep the data in your model in sync with Meilisearch.
```

2024-02-19 16:11 UTC, guimachiavelli commented on learn/cookbooks/laravel-scout.mdx
> +We built an example application to demonstrate how to use Meilisearch with Laravel Scout. It showcases an app-wide search in a CRM (Customer Relationship Management) application.
```suggestion
You built an example application to demonstrate how to use Meilisearch with Laravel Scout. It showcases an app-wide search in a CRM (Customer Relationship Management) application.
```

2024-02-19 16:11 UTC, guimachiavelli commented on learn/cookbooks/laravel-scout.mdx
> +Let’s configure Laravel Scout to use the Meilisearch driver. First, install the dependencies required to use Scout with Meilisearch via Composer:
```suggestion
Now you need to configure Laravel Scout to use the Meilisearch driver. First, install the dependencies required to use Scout with Meilisearch via Composer:
```

2024-02-19 16:11 UTC, guimachiavelli commented on learn/cookbooks/laravel-scout.mdx
> +After installing Scout, you need to publish the Scout configuration file. You can do this by running the following artisan command:
```suggestion
After installing Scout, you need to publish the Scout configuration file. You can do this by running the following `artisan` command:
```

2024-02-19 16:13 UTC, guimachiavelli commented
Oh, and do run linters to check for style errors and broken links. I see the action already reported a few broken links we need to fix before merging.

2024-02-19 16:39 UTC, Strift reviewed
> looks good. Very concise and to the point
😌 😌 😌 

Thanks for the review! I accepted all suggestions to make the tone more in line with what we have already.

Also rewrote the sections you suggested. I leave it up to you to close the relevant discussion if you think we're good 🙏

2024-02-19 16:39 UTC, Strift commented on learn/cookbooks/laravel-scout.mdx
> +Laravel’s official Docker development environment, Laravel Sail, comes with a Meilisearch service out-of-the-box. Please note that when running Meilisearch via Sail, Meilisearch’s host is `http://mei
A "service" is what Docker compose calls each of the "instances" that are run. I understand the fear for unnecessary confusion. 

But on the other hand, for someone familiar with Docker compose, it's  clear. It's the name that they should use to google or search in the Docker docs

2024-02-20 16:49 UTC, guimachiavelli submitted a review, later dismissed
LGTM, but there are a couple of things we need to do before we can merge this:

1. Fix the broken link errors: I believe this means you'll have to remove the fathom stuff until we can get basement to improve the checker, otherwise github won't let us merge into `main`
2. Fix the merge conflict: we recently merged the other laravel guide which altered the same lines of `sidebar_learn.json`. Should be a simple matter of ensuring both objects (the menu items for each guide) are present and well-formatted

2024-02-20 17:10 UTC, Strift commented
@guimachiavelli Fixed both 👍

2024-02-21 10:05 UTC, CaroFG approved these changes
LGTM!

2024-02-21 12:32 UTC, merged