Handling large documents guide
meilisearch/documentation pull request #2767
Opened 2024-03-20 15:51 UTC by guimachiavelli

Closes #310

2024-03-27 07:44 UTC, Kerollmops requested changes

2024-03-27 17:39 UTC, guimachiavelli commented on learn/cookbooks/improving_relevancy_large_documents.mdx
> +description: Use JavaScript with Node.js to split a single large and configure Meilisearch with a distinct attribute to prevent duplicated results.
oops, thanks for spotting that 🤦

2024-03-27 21:38 UTC, curquiza commented
It's happening!! 🎉

2024-03-28 16:04 UTC, guimachiavelli commented
Thanks for the feedback, @kero. I corrected the numbers for what Meilisearch considers a large document according to your recommendation (not really sure where I got the initial numbers, but I did think they were much larger than what I would have expected).

2024-03-28 16:06 UTC, Kerollmops submitted a review, later dismissed
That's perfect! Thank you Gui 😃

2024-03-29 08:58 UTC, Kerollmops submitted a review, later dismissed
LGTM 👌

2024-04-17 11:36 UTC, merged