Update comparison_to_alternatives.mdx
meilisearch/documentation pull request #2771
Opened 2024-03-21 14:55 UTC by gmourier

TBD

2024-03-21 16:49 UTC, gmourier commented on learn/what_is_meilisearch/comparison_to_alternatives.mdx
> +| Compression Support | Gzip, Deflate, Brotli | Gzip | ❌ | Gzip |
Elasticsearch compression support to be completed

2024-03-21 18:36 UTC, guimachiavelli submitted a review, later dismissed

2024-03-22 07:10 UTC, gmourier commented on learn/what_is_meilisearch/comparison_to_alternatives.mdx
> +| Compression Support | Gzip, Deflate, Brotli | Gzip | ❌ | Gzip |
I can only find about Gzip support so far

2024-03-24 13:18 UTC, Kerollmops requested changes

2024-03-25 14:12 UTC, Kerollmops approved these changes
I love the changes 👍

2024-03-26 14:01 UTC, gmourier commented
Ready to get go, @guimachiavelli! 🚂 Thanks!

2024-03-27 17:24 UTC, guimachiavelli approved these changes

2024-03-28 13:54 UTC, merged