add bors and change github action
meilisearch/documentation pull request #530
Opened 2020-10-01 12:20 UTC by bidoubiwa

2020-10-01 12:20 UTC, bidoubiwa commented
bors try

2020-10-01 12:25 UTC, bidoubiwa commented
bors r+

2020-10-01 12:44 UTC, curquiza submitted a review, later dismissed

2020-10-01 12:44 UTC, bidoubiwa commented
bors merge

2020-10-06 13:28 UTC, curquiza requested changes

2020-10-06 13:28 UTC, curquiza commented on .github/workflows/check-links.yml
> +      - staging
```suggestion
      - staging
      - master
```

2020-10-06 13:28 UTC, curquiza commented on .github/workflows/check-links.yml
> +  push:
```suggestion
  # trying and staging branches are for BORS config
  push:
```

2020-10-06 13:28 UTC, curquiza commented on .github/workflows/check-style.yml
> +  push:
```suggestion
  # trying and staging branches are for BORS config
  push:
```

2020-10-06 13:28 UTC, curquiza commented on .github/workflows/check-style.yml
> +      - staging
```suggestion
      - staging
      - master
```

2020-10-06 13:28 UTC, curquiza commented on .github/workflows/gh-pages-scraping.yml
> +    name: build github pages
No `push` event configuration in this file?

```yml
on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - master
```

2020-10-06 14:55 UTC, bidoubiwa commented
bors try

2020-10-06 15:04 UTC, bidoubiwa commented
bors merge

2020-12-08 13:50 UTC, bidoubiwa commented
Will work once this issue is fixed: https://github.com/meilisearch/documentation/issues/551

2020-12-28 19:44 UTC, fharper commented
@bidoubiwa I changed the status to draft since we are waiting for a bug to be fixed.

2021-01-13 22:30 UTC, react-learner commented
🚨 Blocked by #551 🚨

2021-06-10 11:57 UTC, curquiza commented
This PR is replaced #977 
#551 is not blocking to add bors but is still an issue to fix 😇

2021-06-10 11:57 UTC, closed without merging