Modification of the default values on advanced_guides/search_parameters.md and references/search.md and [*] -> ["*"]
meilisearch/documentation pull request #540
Opened 2020-10-05 17:05 UTC by nicolasvienot

This PR includes :
Adding empty string as a default value for q in references/search.md and advanced_guides/search_parameters.md
Modifying all [*] to ["*"] (as in default value for attributesToRetrieve for example)
Changing POST and GET default values on references/search.md, taking into example the ones in advanced_guides/search_parameters.md

Closes #539

2020-10-05 17:13 UTC, nicolasvienot commented
Server reply on get query shows empty string as a default value for `q`.

![query_meilisearch_no_q](https://user-images.githubusercontent.com/44903069/95110777-d81bcf00-073e-11eb-9f0f-686cb7efd8d9.png)

2020-10-06 14:51 UTC, bidoubiwa requested changes
LGTM. Thanks a lot for your contribution. Would you like a hacktoberfest tag?

2020-10-06 14:52 UTC, bidoubiwa submitted a review, later dismissed

2020-10-07 15:06 UTC, nicolasvienot commented
@bidoubiwa Yes, that would be nice! :blush:

2020-10-08 09:30 UTC, bidoubiwa commented
It is added, could you [rebase](https://gist.github.com/curquiza/5f7ce615f85331f083cd467fc4e19398) please?

2020-10-08 14:33 UTC, nicolasvienot commented
> It is added, could you [rebase](https://gist.github.com/curquiza/5f7ce615f85331f083cd467fc4e19398) please?

Should be okay now :thumbsup:

2020-10-08 14:43 UTC, merged