Frontend disable
meilisearch/documentation pull request #613
Opened 2020-11-23 13:04 UTC by MarinPostma

documents https://github.com/meilisearch/MeiliSearch/pull/1097, according to https://github.com/meilisearch/specifications/blob/master/text/0001-frontend-disable-prod.md

2020-11-23 13:23 UTC, curquiza commented
I think we should merge this branch into the `prepare-meilisearch-12-2020` branch instead of the `master` one => https://github.com/meilisearch/documentation/pull/602
Right?

2020-11-26 09:34 UTC, tpayet commented
Hey @react-learner, could you confirm these changes are sufficient and that we are not missing any other parts of the documentation where we could document that? (spoiler alert: it should not 🤞)

2020-12-02 09:37 UTC, react-learner requested changes
Looks good.

2020-12-02 09:37 UTC, react-learner commented on guides/advanced_guides/web_interface.md
> +After adding documents to your MeiliSearch, it is possible to try out the search engine with the integrated web interface. This only works in a [development environment](/guides/advanced_guides/confi
```suggestion
After adding documents to your MeiliSearch, it is possible to try out the search engine with the integrated web interface. This only works in a [development environment](/guides/advanced_guides/configuration.md#environment).
```

2020-12-02 13:30 UTC, merged