Fixes small erros in the code samples
meilisearch/documentation pull request #666
Opened 2021-01-01 13:33 UTC by cies

Now that I have your attention:

* frickin' love MeiliSearch!
* the API likes queries as POSTs (especially when facet params are given), this is against the HTTP spec and has some potential issues (with caching for instance); it would be great to explain this in the docs somewhere and/or find a way to do all retrieve queries as GETs
* the operators (i.e.: `=`, `!=`, etc.) are not clearly explained when it comes to facets on array properties, like: what does `lang != "pt"` do on `lang = ["pt", "pt-BR"]`?
* consider dropping the `$` at the start of each line in the bash/curl examples (makes 'm more copy pastable)

2021-01-04 10:37 UTC, eskombro requested changes
Hello! Just passing by to say that I see a lot of `-X POST` and `-X DELETE` options have been removed in this PR, and this will probably brake several samples. I added some suggestions to show where the problem may be, but they are definitely not exhaustive!

2021-01-04 10:37 UTC, eskombro commented on .code-samples.meilisearch.yaml
> +  $ curl 'http://localhost:7700/indexes' \
```suggestion
  $ curl -X POST 'http://localhost:7700/indexes' \
```

2021-01-04 10:37 UTC, eskombro commented on .code-samples.meilisearch.yaml
> +  $ curl 'http://localhost:7700/indexes/movies/documents' \
```suggestion
  $ curl -X POST 'http://localhost:7700/indexes/movies/documents' \
```

2021-01-04 10:37 UTC, eskombro commented on .code-samples.meilisearch.yaml
> +  $ curl 'http://localhost:7700/indexes/movies/documents' \
```suggestion
  $ curl -X POST 'http://localhost:7700/indexes/movies/documents' \
```

2021-01-04 10:37 UTC, eskombro commented on .code-samples.meilisearch.yaml
> +  curl 'http://localhost:7700/indexes/movies/documents/delete-batch' \
```suggestion
  curl -X DELETE 'http://localhost:7700/indexes/movies/documents/delete-batch' \
```

2021-01-04 16:25 UTC, fharper commented
Thanks for your first PR @cies 🎉

When you have time, please fix the issues highlighted by @eskombro and once done, @react-learner will review the PR.

2021-01-13 17:09 UTC, react-learner commented
Hey @cies , I'm closing this PR for now. If you'd like to continue working on it again, feel free to reopen it!

2021-01-13 17:09 UTC, closed without merging