Update DO how-to v0.18.1
meilisearch/documentation pull request #710
Opened 2021-01-19 15:19 UTC by eskombro

Changes to the DigitalOcean how-to

- Use `meilisearch` user to connect, instead of root
-

2021-01-19 15:21 UTC, eskombro commented
@react-learner this PR is ready, and even if it shouldn't be merged for now (since we are waiting for the DO review process) you can review it if you feel like it :)

2021-01-19 15:50 UTC, curquiza requested changes
I like these explanations!

2021-01-19 15:50 UTC, curquiza commented on resources/howtos/digitalocean_droplet.md
> +Meilisearch is running in a DEVELOPMENT environment. You haven't set up an API KEY (anyone can read/write from your MeiliSearch) and you aren't using HTTPS yet, which makes this configuration uinsafe
```suggestion
Meilisearch is running in a DEVELOPMENT environment. You haven't set up an API KEY (anyone can read/write from your MeiliSearch) and you aren't using HTTPS yet, which makes this configuration unsafe to use in PRODUCTION.
To start the configuration process, connect via SSH to your new MeiliSearch Droplet and follow the instructions:
```

2021-01-19 15:50 UTC, curquiza commented on resources/howtos/digitalocean_droplet.md
> +ssh meilisearch@42.42.42.42
```suggestion
$ ssh meilisearch@42.42.42.42
```

2021-01-19 15:50 UTC, curquiza commented on resources/howtos/digitalocean_droplet.md
> +meilisearch-setup
```suggestion
$ meilisearch-setup
```

2021-01-27 09:29 UTC, curquiza approved these changes

2021-01-27 18:28 UTC, react-learner requested changes
LGreatTM 😄 would maybe be nice to replace some of the ALL CAPS with **bold** to make it more consistent with the rest of the docs. But we can always do that later 😌

2021-01-27 22:38 UTC, curquiza approved these changes

2021-02-01 20:24 UTC, react-learner approved these changes

2021-02-01 20:25 UTC, merged