Add information about ranking rules
meilisearch/documentation pull request #905
Opened 2021-04-13 15:28 UTC by curquiza

Hello @react-learner, here is a behavior we've found out with the core team about ranking rule. No user complained for the moment, but I think the documentation should be transparent about it 🙂

Sorry for my English, I hope this is understandable.
In other words: because of the bucket sort, if the users don't provide documents with the field that they filled in the ranking rules, the search engine cannot behave in a "logical" way. This can lead to some undefined behavior (from the user POV), that's why we recommend having documents containing the fields in the ranking rules.

2021-04-13 15:41 UTC, react-learner commented
So, if I understand right, this is only with the custom ranking rule e.g. if I added `desc(year)` as a ranking rule but had some documents without the `year` attribute, that would cause undefined behavior?

2021-04-13 15:42 UTC, curquiza commented
> So, if I understand right, this is only with the custom ranking rule e.g. if I added desc(year) as a ranking rule but had some documents without the year attribute, that would cause undefined behavior?

Yes! 🙂

2021-04-13 16:33 UTC, react-learner requested changes
Looks good, thanks!

2021-04-13 16:33 UTC, react-learner commented on reference/features/settings.md
> +We recommend providing documents that all contain the attribute filled in the ranking rule.
```suggestion

We recommend that all your documents contain any attribute used in a custom ranking rule. For example, if you set the custom ranking rule `desc(year)`, make sure that all your documents contain the attribute `year`.
```

2021-04-14 08:46 UTC, react-learner approved these changes
LGTM! Thanks ❤️

2021-04-14 08:47 UTC, merged