Update quick start page
meilisearch/documentation pull request #946
Opened 2021-05-27 14:31 UTC by guimachiavelli

Specify user needs to download movies.json file

2021-05-27 14:39 UTC, dichotommy requested changes
Looks good, just a small wording change!

2021-05-27 14:39 UTC, dichotommy commented on learn/getting_started/quick_start.md
> +Below is an example to showcase how to add documents to an index called `movies` using the following test dataset: [movies.json](https://raw.githubusercontent.com/meilisearch/MeiliSearch/master/datas
```suggestion
Below is an example to showcase how to add documents to an index called `movies`. To follow along, first right click this link and download the file: [movies.json](https://raw.githubusercontent.com/meilisearch/MeiliSearch/master/datasets/movies/movies.json). Then, move the downloaded file to your working directory.
```

2021-05-31 15:05 UTC, guimachiavelli commented on learn/getting_started/quick_start.md
> +Below is an example to showcase how to add documents to an index called `movies`. To follow along, first right click this link and download the file: [movies.json](https://raw.githubusercontent.com/m
```suggestion
Below is an example to showcase how to add documents to an index called `movies`. To follow along, first right-click this link and download the file: [movies.json](https://raw.githubusercontent.com/meilisearch/MeiliSearch/master/datasets/movies/movies.json). Then, move the downloaded file to your working directory.
```

2021-05-31 15:24 UTC, dichotommy approved these changes
Looks good to me! Since this PR has a few commits (including one unnecessary merge commit), I would recommend using `Rebase & Merge` (should get rid of that merge commit).

2021-06-01 09:23 UTC, merged